application/routes.py
"""Main routes."""
from flask.cli import with_appcontext
from flask import url_for, render_template, request
import json
from flask import current_app as app
from flask import Blueprint
from flask_login import login_required


main_bp = Blueprint('main', __name__)


@main_bp.route("/dashboard", methods=['GET', 'POST'])
@login_required
def dashboard():
    """Landing Page Dashboard."""
    return render_template('/dashboard.html', data=g.db['onboarding'], template="dashboard-template")


@main_bp.route("/frame", methods=['GET', 'POST'])
@login_required
def frame():
    app.template_folder = 'templates'
    return render_template('/frame.html',)


@main_bp.route('/question', methods=['GET', 'POST'])
@login_required
def question():
    """Entry point for quetions."""
    return render_template('/question.html', template='qotd-template')


@main_bp.route('/discover', methods=['GET', 'POST'])
@login_required
def discover():
    """Entry point for discover."""
    return render_template('/discover.html', template='questionaire-template')


@main_bp.route('/interact', methods=['GET', 'POST'])
@login_required
def interact():
    """Audio submission portal."""
    return render_template('/interact.html', template='interact-template')


@main_bp.route('/onboarding-business', methods=['GET', 'POST'])
@login_required
def onboardingbusiness():
    """User business-type onboarding."""
    data = json.loads(onboarding)
    return render_template('/onboarding.html', category=data.category, questiontext=data.question)


@main_bp.route('/onboarding-customers', methods=['GET', 'POST'])
@login_required
def onboardingcustomers():
    """User onboarding question."""
    return render_template('/onboarding.html', category='customers', questiontext='What stage are you at in customer understanding?')


@main_bp.route('/onboarding-competition', methods=['GET', 'POST'])
def onboardingcompetition():
    """User competition onboarding."""
    return render_template('/onboarding.html', category='competition', questiontext='What stage are your competitors at?')


@main_bp.route('/onboarding-team', methods=['GET', 'POST'])
def onboardingteam():
    """User team onboarding."""
    return render_template('/onboarding.html', category='team', questiontext='What stage is your team development at?')

application/templates/dashboard.html
{% extends "layout.html" %}

  {% block pagestyles %}
    <link href="{{ url_for('static', filename='dist/css/components/dashboard.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='dist/css/components/nav.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='dist/css/components/onboarding.css') }}" rel="stylesheet">
  {% endblock %}

  {% block content %}
  <div class="dashlayout">
    <div class="sidebar">
      <div class="logo" style="{{ url_for('static', filename='img/logo_dark.png') }}"></div>
      {% include 'nav.html' %}
    </div>
    <div class="onboarding">
      {% include 'onboarding.html' %}
    </div>
  </div>
  <a class="nextquestion">
    <div class="nexttext">NEXT</div>
    <div class="nextarrow"></div>
  </a>
  {% include 'footer.html' %}
  {% endblock %}

application/templates/discover.html
{% extends "dashboard.html" %}

{% block sectionstyle %}
  {% assets "scss_all" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet">
  {% endassets %}
{% endblock %}

{% block content %}
<div class="{{template}}">
  <div class="holder">
    <div class="shape"></div>
    <h1>Profile</h1>
  </div>

  <div class="question">
    <h5>tell us more about your:<h5>
  </div>

  <div class="categories">
    <div class="category business"></div>
    <div class="category customers"></div>
    <div class="category competition"></div>
    <div class="category team"></div>
</div>
</div>
{% endblock %}

application/templates/footer.html
<footer>
  <hr>
    <img src="{{ url_for('static', filename='img/dh.png') }}">
  <hr>
</footer>

application/templates/frame.html
{% extends "layout.html" %}

{% block head %}
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.2/src/chart.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.2/dist/Chart.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.2/dist/Chart.bundle.min.js"></script>
{% endblock %}

{% block content %}
  <canvas id="myChart" width="400" height="400"></canvas>

  <script>
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>
{% endblock %}

application/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% include 'meta.html' %}
  {% block pagestyles %}{% endblock %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css"> -->
</head>
<body class="{{template}}">
  <div class="container">
	  {% block content %}{% endblock %}
  </div>
</body>

{% include 'scripts.html' %}

{% block additionalscripts %}{% endblock %}
</html>

application/templates/login.html
{% extends "layout.html" %}

{% block pagestyles %}
  {% assets "scss_all" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet">
  {% endassets %}
{% endblock %}

 {% block content %}
<div class="formwrapper">
<form method=post>
  <div class="logo">
    <img src="{{ url_for('static', filename='img/logo_dark.png') }}">
  </div>
  <div class="email">
     {{ form.email(placeholder='David Hunt') }}
     {{ form.email.label }}
  </div>
  <div class="password">
    {{ form.password }}
    {{ form.password.label }}
  </div>
  <div class="submitbutton">
    <input id="submit" type="submit" value="Submit">
  </div>
</form>
</div>

{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}

{% endblock %}

application/templates/meta.html
{% block meta %}
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<title>Framewrk Agency</title>
<meta name="HandheldFriendly" content="True" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon/Favicon48w.png') }}" type="image/x-icon"/>
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-TXfwrfuHVznxCssTxWoPZjhcss/hp38gEOH8UPZG/JcXonvBQ6SlsIF49wUzsGno" crossorigin="anonymous"><!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-121192304-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
    dataLayer.push(arguments);
  }
  gtag('js', new Date());
  gtag('config', 'UA-121192304-1');
</script>
{% endblock %}

application/templates/mobilenav.html
  <nav> <!-- navbar content here  --> </nav>

  <ul id="slide-out" class="sidenav">
    <li><div class="user-view">
      <div class="background">
        <img src="images/office.jpg">
      </div>
      <a href="#user"><img class="circle" src="images/yuna.jpg"></a>
      <a href="#name"><span class="white-text name">John Doe</span></a>
      <a href="#email"><span class="white-text email">jdandturk@gmail.com</span></a>
    </div></li>
    <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
    <li><a href="#!">Second Link</a></li>
    <li><div class="divider"></div></li>
    <li><a class="subheader">Subheader</a></li>
    <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
  </ul>
  <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>

application/templates/nav.html
<nav>
    <ul>
      <a href="{{ url_for('main.question') }}" data-toggle="tooltip" title="" data-original-title="Question of the year"><li class="question">Question</li></a>
      <a href="{{ url_for('main.discover') }}" data-toggle="tooltip" title="" data-original-title="Grow your business"><li class="discover">Discover</li></a>
      <a href="{{ url_for('main.interact') }}" data-toggle="tooltip" title="" data-original-title="Talk it out"><li class="interact">Interact</li></a>
    </ul>
</nav>

application/templates/onboarding.html
{% for step in data %}
<div class="onboardingarea">
  <div class="pedestal">
    <div class="shape business {{step.category}}" draggable="true"></div>
  </div>
  <h1 class="category">{{step.category}}</h2>
  <h3 class="question">{{step.question}}</h2>

  <div class="answers">
    <ul>
      {% for answer in step.options %}
      <li>
        <div class="dropzone" data-type="{{answer.name}}"></div>
        <hr>
        <div class="label" data-toggle="tooltip" title="{{answer.tooltip}}">{{answer.name}}</div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
  {% endfor %}

application/templates/roadmapmodal.html
  <div data-target="#myModal" class="card">
    <div class="card-content">
      <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
    </div>
    <div class="card-tabs">
      <ul class="tabs tabs-fixed-width">
        <li class="tab"><a href="#test4">Test 1</a></li>
        <li class="tab"><a class="active" href="#test5">Test 2</a></li>
        <li class="tab"><a href="#test6">Test 3</a></li>
      </ul>
    </div>
    <div class="card-content grey lighten-4">
      <div id="test4">Test 1</div>
      <div id="test5">Test 2</div>
      <div id="test6">Test 3</div>
    </div>
  </div>

application/templates/scripts.html
<!-- Insert this line above script imports  -->
<script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>


<script src="{{ url_for('static', filename='dist/js/includes/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='dist/js/includes/jquery-ui.min.js') }}"></script>
<script src="https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>

<!-- Insert this line after script imports -->
<script>if (window.module) module = window.module;</script>
<script src="{{ url_for('static', filename='dist/js/dragdrop.js') }}"></script>
<script src="{{ url_for('static', filename='dist/js/sidebar.js') }}"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>-->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script> -->

application/templates/signup.html
{% extends "layout.html" %}

{% block pagestyles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='dist/css/forms.css') }}" type="text/css" />
    <link href="{{ url_for('static', filename='dist/css/main.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<div class="formwrapper">
  <form method=post>
    <div class="logo">
      <img src="{{ url_for('static', filename='img/logo_dark.png') }}">
    </div>
    <div class="name">
      {{ form.name(placeholder='David Hunt') }} {{ form.name.label }}
      {% if form.name.errors %}
        <ul class="errors">{% for error in form.name.errors %}<li>{{ error }}</li>{% endfor %}</ul>
      {% endif %}
    </div>
    <div class="email">
      {{ form.email }} {{ form.email.label }}
      {% if form.email.errors %}
        <ul class="errors">{% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}</ul>
      {% endif %}
    </div>
    <div class="password">
      {{ form.password }} {{ form.password.label }}
      {% if form.password.errors %}
        <ul class="errors">{% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}</ul>
      {% endif %}
    </div>
    <div class="confirm">
      {{ form.confirm }} {{ form.confirm.label }}
      {% if form.confirm.errors %}
        <ul class="errors">{% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}</ul>
      {% endif %}
    </div>
    <div class="website">
      {{ form.website(placeholder='http://example.com') }} {{ form.website.label }}
    </div>
    <div class="submitbutton">
      <input id="submit" type="submit" value="Submit">
    </div>
  </form>
  <div class="loginsignup">
    <span>Already have an account? <a href="{{ url_for('auth.login') }}">Log in.</a><span>
    </div>
    <div class="testlink">
      <span><i class="fal fa-exclamation-triangle"></i> FOR TESTING: <a href="{{ url_for('main.dashboard') }}">See Dashboard</a><span>
    </div>
</div>

{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}

{% endblock %}