framewrk/models.py
from flask_login import UserMixin


class User(UserMixin):
    """Model for user accounts."""
    def __init__(self, email):
        self.email = email

    @staticmethod
    def is_authenticated(self):
        self.authenticated = True

    def get_id(self):
        return self.email

    @staticmethod
    def validate_login(password_hash, password):
        return bcrypt.check_password_hash(password_hash, password)

framewrk/forms.py
from flask_wtf import FlaskForm
from wtforms import Form, StringField, PasswordField, validators, SubmitField, SelectField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length


class SignupForm(FlaskForm):
    """User Signup."""

    name = StringField('Name', [
        validators.DataRequired(message=('Don\'t be shy!'))
    ])
    email = StringField('Email', [
        Length(min=6, message=(u'Little short for an email address?')),
        Email(message=('That\'s not a valid email address.')),
        DataRequired(message=('That\'s not a valid email address.'))
    ])
    password = PasswordField('Password', validators=[
        DataRequired(message="Please enter a password."),
    ])
    confirm = PasswordField('Repeat Password', validators=[
        EqualTo(password, message='Passwords must match.')
        ])
    website = StringField('Website')
    submit = SubmitField('Register')


'''   def validate_email(self, email):
        """Email validation."""
        users = g.db
        user = users.find_one({'email': email})
        # user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')
'''


class LoginForm(Form):
    """User Login."""

    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')


class addItems(Form):
    """Add items to roadmap."""

    add = SelectField(label="Add to your roadmap.")
    submit = SubmitField('OK')

framewrk/__init__.py
import os
import sys
from flask import Flask, g
import config
import flask_login
#from flask_pymongo import PyMongo
# from models import User, users, login_manager


def create_app():
    """Construct app."""
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object('config.BaseConfig')
    login = flask_login.LoginManager()

    with app.app_context():
        from . import views
        from . import auth
        login.init_app(app)
        #mongo = PyMongo(app, app.config['MONGO_URI'])
        # g.db = mongo
        app.register_blueprint(auth.auth)
        app.register_blueprint(views.main)

        return app

framewrk/auth.py
import sys
import os
from flask import render_template, redirect, request, flash, g, session, Response, Blueprint
from flask import current_app as app
import json
import sass
import bcrypt
from flask_login import login_user, login_required, logout_user
from flask_assets import Environment, Bundle, build
from forms import LoginForm, SignupForm

auth = Blueprint('auth', __name__)
assets = Environment(app)
scss = Bundle('scss/main.scss', 'scss/components/forms.scss', filters='libsass', output='build/css/style.css')
assets.register('scss_all', scss)
# scss.build(disable_cache=None)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    """Login form."""
    login_form = LoginForm(request.form)
    if request.method == 'GET':
        return render_template('/login.html', form=login_form, template="form-page")
    else:
        if login_form.validate():
            users = 'placeholder'
            existing_user = users.find_one({'email': request.form['email']})
            print('attempted login = ', existing_user)
            sys.stdout.flush()
            if existing_user:
                print('user exists')
                sys.stdout.flush()
                if bcrypt.hashpw(request.form['password'].encode('utf-8'), bcrypt.genSalt()):
                    session['email'] = request.form['email']
                    return render_template('/dashboard.html', template="dashbord-template")
    return 'Invalid username/password combination'


@auth.route('/', methods=['GET', 'POST'])
def signup():
    """Signup Form."""
    signup_form = SignupForm(request.form)
    if request.method == 'POST':
        if signup_form.validate():
            users = mongo.db.users
            existing_user = users.find_one({'email': request.form['email']})
            print('attempted signup = ', existing_user)
            sys.stdout.flush()

            if existing_user is None:
                user_document = {'name': request.form['name'],
                            'email': request.form['email'],
                            'password': bcrypt.hashpw(request.form['password'].encode('utf-8'), bcrypt.genSalt()),
                            'website': request.form['website']
                            }
                users.insertOne({user_document})
                flash('Signed up successfully.')
                redirect(url_for('dashboard'))

            else:
                return 'That username already exists'
    return render_template('/signup.html', form=signup_form, template="form-page")


'''@login_manager.user_loader
def load_user(email):
    users = mongo.db.users
    return users.find_one({'email': email})
'''


# somewhere to logout
@auth.route("/logout")
@login_required
def logout():
    """User explicity logs out."""
    logout_user()
    return Response('<p>Logged out</p>')


# handle login failed
@auth.errorhandler(401)
def page_not_found(e):
    """User attempts to reach broken page."""
    return Response('<p>Login failed</p>')

framewrk/views.py
import os
from flask import url_for, render_template, redirect, request, flash, Session, g
from forms import LoginForm, SignupForm
from flask_login import login_user, login_required
import json
from flask import Blueprint

main = Blueprint('main', __name__)

'''@main.url_value_preprocessor
def url_value_preprocessor(endpoint, values):
    """Validate before every request."""
    if 'username' in session:
        return session
    else:
        if request.args.get('email'):
            session.permanent = True
            email = request.args.get('email')
            username = email.split('@main.')[0]'''


@main.route("/dashboard", methods=['GET', 'POST'])
@login_required
def dashboard():
    """Landing Page Dashboard."""
    return render_template('/dashboard.html', data=g.db['onboarding'], template="dashboard-template")


@main.route("/frame", methods=['GET', 'POST'])
@login_required
def frame():
    main.template_folder = 'templates'
    return render_template('/frame.html',)


@main.route('/question', methods=['GET', 'POST'])
@login_required
def question():
    """Entry point for quetions."""
    return render_template('/question.html', template='qotd-template')


@main.route('/discover', methods=['GET', 'POST'])
@login_required
def discover():
    """Entry point for discover."""
    return render_template('/discover.html', template='questionaire-template')


@main.route('/interact', methods=['GET', 'POST'])
@login_required
def interact():
    """Audio submission portal."""
    return render_template('/interact.html', template='interact-template')


@main.route('/onboarding-business', methods=['GET', 'POST'])
@login_required
def onboardingbusiness():
    """User business-type onboarding."""
    data = json.loads(onboarding)
    return render_template('/onboarding.html', category=data.category, questiontext=data.question)


@main.route('/onboarding-customers', methods=['GET', 'POST'])
@login_required
def onboardingcustomers():
    """User onboarding question."""
    return render_template('/onboarding.html', category='customers', questiontext='What stage are you at in customer understanding?')


@main.route('/onboarding-competition', methods=['GET', 'POST'])
def onboardingcompetition():
    """User competition onboarding."""
    return render_template('/onboarding.html', category='competition', questiontext='What stage are your competitors at?')


@main.route('/onboarding-team', methods=['GET', 'POST'])
def onboardingteam():
    """User team onboarding."""
    return render_template('/onboarding.html', category='team', questiontext='What stage is your team development at?')


@main.route('/directory', methods=['GET'])
def directory():
    """List all templates."""
    test = os.listdir()
    print(test)
    template_urls = os.listdir('framewrk/templates')
    return render_template('/directory.html', templates=template_urls, template='directory-template')

framewrk/templates/dashboard.html
{% extends "layout.html" %}

  {% block pagestyles %}
    <link href="{{ url_for('static', filename='build/css/components/dashboard.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='build/css/components/nav.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='build/css/components/onboarding.css') }}" rel="stylesheet">
  {% endblock %}

  {% block content %}
  <div class="dashlayout">
    <div class="sidebar">
      <div class="logo" style="{{ url_for('static', filename='img/logo_dark.png') }}"></div>
      {% include 'nav.html' %}
    </div>
    <div class="onboarding">
      {% include 'onboarding.html' %}
    </div>
  </div>
  <a class="nextquestion">
    <div class="nexttext">NEXT</div>
    <div class="nextarrow"></div>
  </a>
  {% include 'footer.html' %}
  {% endblock %}

framewrk/templates/directory.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% include 'meta.html' %}
</head>

<body>
<ul>
  {% for result in templates %}
  <li>
    <a href="{{ url_for({{result}}) }}">{{result}}</a>
  </li>
  {% endfor %}
  </ul>
</body>
</html>

framewrk/templates/meta.html
{% block meta %}
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<title>Framewrk Agency</title>
<meta name="HandheldFriendly" content="True" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
<link rel="shortcut icon" href="{{static}}/img/framewrk-icon.jpg" type="image/x-icon"/>
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-TXfwrfuHVznxCssTxWoPZjhcss/hp38gEOH8UPZG/JcXonvBQ6SlsIF49wUzsGno" crossorigin="anonymous"><!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-121192304-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
    dataLayer.push(arguments);
  }
  gtag('js', new Date());
  gtag('config', 'UA-121192304-1');
</script>
{% endblock %}

framewrk/templates/scripts.html
<!-- Insert this line above script imports  -->
<script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>


<script src="{{ url_for('static', filename='js/includes/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/includes/jquery-ui.min.js') }}"></script>
<script src="https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>

<!-- Insert this line after script imports -->
<script>if (window.module) module = window.module;</script>
<script src="{{ url_for('static', filename='js/dragdrop.js') }}"></script>
<script src="{{ url_for('static', filename='js/sidebar.js') }}"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>-->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script> -->

framewrk/templates/signup.html
{% extends "layout.html" %}

{% block pagestyles %}
    <!--<link rel="stylesheet" href="{{ url_for('static', filename='build/css/forms.css') }}" type="text/css" />-->
    <link rel="stylesheet" href="{{ url_for('static', filename='build/css/style.css') }}" type="text/css">
{% endblock %}

{% block content %}
<div class="formwrapper">
  <form method=post>
    <div class="logo">
      <img src="{{ url_for('static', filename='img/logo_dark.png') }}">
    </div>
    <div class="name">
      {{ form.name(placeholder='Joe Smith') }} {{ form.name.label }}
      {% if form.name.errors %}
        <ul class="errors">{% for error in form.name.errors %}<li>{{ error }}</li>{% endfor %}</ul>
      {% endif %}
    </div>
    <div class="email">
      {{ form.email(placeholder='joe.smith@example.com') }} {{ form.email.label }}
      {% if form.email.errors %}
        <ul class="errors">{% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}</ul>
      {% endif %}
    </div>
    <div class="password">
      {{ form.password }} {{ form.password.label }}
      {% if form.password.errors %}
        <ul class="errors">{% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}</ul>
      {% endif %}
    </div>
    <div class="confirm">
      {{ form.confirm }} {{ form.confirm.label }}
      {% if form.confirm.errors %}
        <ul class="errors">{% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}</ul>
      {% endif %}
    </div>
    <div class="website">
      {{ form.website(placeholder='http://example.com') }} {{ form.website.label }}
    </div>
    <div class="submitbutton">
      <input id="submit" type="submit" value="Submit">
    </div>
  </form>
  <div class="loginsignup">
    <span>Already have an account? <a href="{{ url_for('auth.login') }}">Log in.</a><span>
    </div>
    <div class="testlink">
      <span><i class="fal fa-exclamation-triangle"></i> FOR TESTING: <a href="{{ url_for('main.dashboard') }}">See Dashboard</a><span>
    </div>
</div>

{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}

{% endblock %}